branches:
  only:
    - master
language: erlang
otp_release:
  - 22.0
  - 21.3
  - 21.0
  - 20.3
  - 20.0
  - 19.3
  - 19.0
env:
  - LLVM_VERSION=8.0.0
  - LLVM_VERSION=7.0.1
  - LLVM_VERSION=6.0.1
  - LLVM_VERSION=5.0.2
  - LLVM_VERSION=4.0.0
  - LLVM_VERSION=3.8.1
  - LLVM_VERSION=3.5.2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libncurses5
      - libncurses5-dev
      - autoconf
      - libssl-dev
script: "make all"
sudo: false
before_script:
  - ./travis/install_deps.sh
  - make get-deps
  - export LLVM_DIR=$PWD/cache/clang+llvm-$LLVM_VERSION
  - export PATH=$LLVM_DIR/bin:$PATH
  - export LD_LIBRARY_PATH=$LLVM_DIR/lib
  - export NIFTY_ROOT=$PWD
  - clang --version             # just for sanity
after_failure:
  - ./travis/after_failure.sh
cache:
  directories:
    - cache
