language: erlang
otp_release:
  - 18.1
  - 18.0
  - 17.4
  - 17.0
env:
  - CPATH=/usr/lib/llvm-3.4/include LIBRARY_PATH=/usr/lib/llvm-3.4/lib LD_LIBRARY_PATH=/usr/lib/llvm-3.4/lib
  - CPATH=/usr/lib/llvm-3.6/include LIBRARY_PATH=/usr/lib/llvm-3.6/lib LD_LIBRARY_PATH=/usr/lib/llvm-3.6/lib
  - CPATH=/usr/lib/llvm-3.7/include LIBRARY_PATH=/usr/lib/llvm-3.7/lib LD_LIBRARY_PATH=/usr/lib/llvm-3.7/lib
  - CPATH=/usr/lib/llvm-3.8/include LIBRARY_PATH=/usr/lib/llvm-3.8/lib LD_LIBRARY_PATH=/usr/lib/llvm-3.8/lib
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
    packages:
      - libclang1-3.4
      - libclang1-3.6
      - libclang1-3.7
      - libclang1-3.8
      - libclang-3.4-dev
      - libclang-3.6-dev
      - libclang-3.7-dev
      - libclang-3.8-dev
script: "make all"
cache: apt
sudo: false
