branches:
  only:
    - master
language: erlang
otp_release:
  - 20.3
  - 20.0
  - 19.3
  - 19.0
  - 18.3
  - 18.0
  - 17.4
  - 17.0
env:
  - LLVM_VERSION=3.9.0
  - LLVM_VERSION=3.8.1
  - LLVM_VERSION=3.7.1
  - LLVM_VERSION=3.6.2
  - LLVM_VERSION=3.5.2
matrix:
  include:
    - language: c
      env: >
        LLVM_VERSION=3.9.0
        TRAVIS_OTP_RELEASE=19.2.dirtyschedulers
        PATH=cache/OTP_19_INSTALL/bin:$PATH
        CPATH=$PWD/cache/OTP_19_INSTALL/lib/erlang/include
        LD_LIBRARY_PATH=$PWD/cache/OTP_19_INSTALL/lib/erlang/lib
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libncurses5
      - libncurses5-dev
      - autoconf
      - libssl-dev
script: "make all rebar_regression"
sudo: false
before_cache:
  - ./travis/store_plt.sh
before_script:
  - ./travis/install_deps.sh
  - make get-deps
  - export LLVM_DIR=$PWD/cache/clang+llvm-$LLVM_VERSION
  - export PATH=$LLVM_DIR/bin:$PATH
  - export LD_LIBRARY_PATH=$LLVM_DIR/lib
  - export CPATH=/usr/lib/gcc/x86_64-linux-gnu/4.9/include
  - export NIFTY_ROOT=$PWD
after_failure:
  - ./travis/after_failure.sh
cache:
  directories:
    - cache
