title:            Nifty - NIF Interface Generator
description:      New, Documentation and Tutorials of Nifty
# Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://130.238.11.192:4000
url: http://parapluu.github.io/nifty/
#url:              http://localhost:4000
disqus_shortname: 

# Owner/author information
owner:
  name:           Nifty
  avatar:         avatar.png
  bio:            "Nifty - NIF interface generator"
  email:         
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        
  facebook:       
  github:         parapluu/nifty
  stackoverflow: 
  linkedin:       
  instagram:      
  lastfm:         
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: API Documentation
    url: /api-doc/index.html
  - title: Install Nifty
    url: /install
  - title: Tutorials
    url: /tutorial
  - title: GitHub
    url: https://github.com/parapluu/nifty
    external: true
#  - title: Theme Setup
#    url: /theme-setup

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
